#!/bin/bash
#while [[ 1 -lt 2 ]]
 #do
 # read hello
 # sleep 1
 #done

#!/bin/bash

#while true; do
# read -p "hello> " input
#  if [ "$input" == "exit" ]; then
#  break
#  fi
#done


#!/bin/bash

input="alex"

# Loop until input is "exit"
while [ "$input" != "exit" ]; do
	    read -p "hello> " input
    done

